CREATE TABLE IF NOT EXISTS team_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  equipe VARCHAR(50) DEFAULT NULL,
  titulo VARCHAR(255) DEFAULT NULL,
  descricao TEXT,
  status VARCHAR(30) DEFAULT 'Pendente',
  responsavel VARCHAR(100),
  team_id INT DEFAULT NULL,
  data_vencimento DATE,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
