-- Database schema for crm_wrsolar

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  cidade VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  cpf_cnpj VARCHAR(20) DEFAULT NULL,
  source VARCHAR(100) DEFAULT NULL,
  status VARCHAR(100) DEFAULT 'Novo',
  notes TEXT DEFAULT NULL,
  consumo_cliente DECIMAL(10,2) DEFAULT NULL,
  estimativa_projeto_kwh DECIMAL(10,2) DEFAULT NULL,
  orcamento_value DECIMAL(12,2) DEFAULT 0.00,
  anexos LONGBLOB DEFAULT NULL,
  anexos_filename VARCHAR(255) DEFAULT NULL,
  anexos_mimetype VARCHAR(100) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projetos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  client_name VARCHAR(255) NOT NULL,
  address TEXT DEFAULT NULL,
  proposal_value DECIMAL(12,2) DEFAULT 0.00,
  status VARCHAR(100) DEFAULT 'Prospec\u00e7\u00e3o',
  lead_id INT DEFAULT NULL,
  closed_date DATETIME DEFAULT NULL,
  contract TEXT DEFAULT NULL,
  projeto VARCHAR(255) DEFAULT NULL,
  client_status VARCHAR(50) DEFAULT 'Assinante',
  payment_type VARCHAR(50) DEFAULT NULL,
  logistics_tracking_code VARCHAR(255) DEFAULT NULL,
  logistics_delivery_date DATE DEFAULT NULL,
  inspection_photos TEXT DEFAULT NULL,
  technical_checklist TEXT DEFAULT NULL,
  docs_checklist TEXT DEFAULT NULL,
  doc_attachments TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pos_venda (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  project_id INT DEFAULT NULL,
  client_name VARCHAR(255) NOT NULL,
  installation_date DATE DEFAULT NULL,
  next_maintenance DATE DEFAULT NULL,
  warranty_end DATE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projetos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Migration script: add tabela para etapas de projetos

CREATE TABLE IF NOT EXISTS projeto_stages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  position INT NOT NULL DEFAULT 0,
  is_initial TINYINT(1) NOT NULL DEFAULT 0,
  color VARCHAR(7) DEFAULT '#6c757d',
  card_color VARCHAR(7) DEFAULT '#ffffff',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projeto_stages_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stage_id INT NULL,
  user_id INT NULL,
  action VARCHAR(50) NOT NULL,
  changes JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (stage_id),
  INDEX (user_id),
  FOREIGN KEY (stage_id) REFERENCES projeto_stages(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
