-- Database schema for crm_wrsolar

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nome_completo VARCHAR(255) DEFAULT NULL,
  biografia TEXT DEFAULT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  cidade VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  cpf_cnpj VARCHAR(20) DEFAULT NULL,
  source VARCHAR(100) DEFAULT NULL,
  is_ad_source TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(100) DEFAULT 'Novo',
  notes TEXT DEFAULT NULL,
  consumo_cliente DECIMAL(10,2) DEFAULT NULL,
  estimativa_projeto_kwh DECIMAL(10,2) DEFAULT NULL,
  orcamento_value DECIMAL(12,2) DEFAULT 0.00,
  anexos LONGBLOB DEFAULT NULL,
  anexos_filename VARCHAR(255) DEFAULT NULL,
  anexos_mimetype VARCHAR(100) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS projetos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  client_name VARCHAR(255) NOT NULL,
  address TEXT DEFAULT NULL,
  proposal_value DECIMAL(12,2) DEFAULT 0.00,
  status VARCHAR(100) DEFAULT 'Prospec\u00e7\u00e3o',
  status_changed_at DATETIME DEFAULT NULL,
  moved_to_post_sale TINYINT(1) NOT NULL DEFAULT 0,
  lead_id INT DEFAULT NULL,
  closed_date DATETIME DEFAULT NULL,
  contract TEXT DEFAULT NULL,
  projeto VARCHAR(255) DEFAULT NULL,
  client_status VARCHAR(50) DEFAULT 'Assinante',
  payment_type VARCHAR(50) DEFAULT NULL,
  payment_status VARCHAR(50) DEFAULT NULL,
  logistics_tracking_code VARCHAR(255) DEFAULT NULL,
  logistics_delivery_date DATE DEFAULT NULL,
  inspection_photos TEXT DEFAULT NULL,
  technical_checklist TEXT DEFAULT NULL,
  docs_checklist TEXT DEFAULT NULL,
  doc_attachments TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pos_venda (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  project_id INT DEFAULT NULL,
  client_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  kit VARCHAR(255) DEFAULT NULL,
  marca VARCHAR(255) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  installation_date DATE DEFAULT NULL,
  next_maintenance DATE DEFAULT NULL,
  warranty_end DATE DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projetos(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS pos_venda_referrals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pos_venda_id INT NOT NULL,
  user_id INT NOT NULL,
  referral_token VARCHAR(64) NOT NULL,
  indicator_name VARCHAR(255) NOT NULL,
  indicator_phone VARCHAR(50) DEFAULT NULL,
  indicator_email VARCHAR(255) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (pos_venda_id) REFERENCES pos_venda(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY ux_pos_venda_referrals_token (referral_token)
);

CREATE TABLE IF NOT EXISTS project_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  project_id INT NOT NULL,
  user_id INT NOT NULL,
  action VARCHAR(100) NOT NULL,
  from_status VARCHAR(100) DEFAULT NULL,
  to_status VARCHAR(100) DEFAULT NULL,
  from_client_status VARCHAR(50) DEFAULT NULL,
  to_client_status VARCHAR(50) DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_project_movements_project (project_id),
  INDEX idx_project_movements_user (user_id),
  FOREIGN KEY (project_id) REFERENCES projetos(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pos_venda_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pos_venda_id INT NOT NULL,
  project_id INT DEFAULT NULL,
  user_id INT NOT NULL,
  action VARCHAR(100) NOT NULL,
  from_stage VARCHAR(255) DEFAULT NULL,
  to_stage VARCHAR(255) DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pos_venda_movements_pv (pos_venda_id),
  INDEX idx_pos_venda_movements_project (project_id),
  INDEX idx_pos_venda_movements_user (user_id),
  FOREIGN KEY (pos_venda_id) REFERENCES pos_venda(id) ON DELETE CASCADE,
  FOREIGN KEY (project_id) REFERENCES projetos(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Migration script: add tabela para etapas de projetos

CREATE TABLE IF NOT EXISTS projeto_stages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  position INT NOT NULL DEFAULT 0,
  is_initial TINYINT(1) NOT NULL DEFAULT 0,
  color VARCHAR(7) DEFAULT '#6c757d',
  card_color VARCHAR(7) DEFAULT '#ffffff',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS projeto_stages_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stage_id INT NULL,
  user_id INT NULL,
  action VARCHAR(50) NOT NULL,
  changes JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (stage_id),
  INDEX (user_id),
  FOREIGN KEY (stage_id) REFERENCES projeto_stages(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Additional tables referenced by the application

CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  role_id INT NOT NULL,
  screen VARCHAR(255) NOT NULL,
  allowed TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alerts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  project_id INT DEFAULT NULL,
  type VARCHAR(100) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  equipe VARCHAR(255) DEFAULT NULL,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT DEFAULT NULL,
  status VARCHAR(50) DEFAULT 'open',
  responsavel VARCHAR(255) DEFAULT NULL,
  responsavel_id INT DEFAULT NULL,
  data_vencimento DATE DEFAULT NULL,
  lead_id INT DEFAULT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS team_tasks_activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  task_id INT DEFAULT NULL,
  action VARCHAR(255) NOT NULL,
  user_id INT DEFAULT NULL,
  username VARCHAR(255) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  equipe VARCHAR(255) DEFAULT NULL,
  titulo VARCHAR(255) DEFAULT NULL,
  responsavel VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reminder_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  message TEXT DEFAULT NULL,
  default_days_offset INT DEFAULT NULL,
  default_time VARCHAR(10) DEFAULT NULL,
  channel VARCHAR(50) DEFAULT NULL,
  created_by INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  active TINYINT(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS reminders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT DEFAULT NULL,
  message TEXT DEFAULT NULL,
  remind_at DATETIME DEFAULT NULL,
  template_id INT DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  created_by INT DEFAULT NULL,
  contact_name VARCHAR(255) DEFAULT NULL,
  contact_phone VARCHAR(50) DEFAULT NULL,
  responsavel_id INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_statuses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  position INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS payment_methods (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS activity_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  action VARCHAR(255) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS funil_stages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  position INT DEFAULT 0,
  color VARCHAR(7) DEFAULT '#6c757d',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS funil_stages_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  stage_id INT DEFAULT NULL,
  user_id INT DEFAULT NULL,
  action VARCHAR(100) NOT NULL,
  changes JSON DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  user_id INT DEFAULT NULL,
  from_status VARCHAR(100) DEFAULT NULL,
  to_status VARCHAR(100) DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lead_update_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  user_id INT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_lead_update_logs_created_user (created_at, user_id),
  INDEX idx_lead_update_logs_lead (lead_id)
);

CREATE TABLE IF NOT EXISTS leads_anuncios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  source VARCHAR(255) DEFAULT NULL,
  details TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads_attachments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  lead_id INT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  filepath VARCHAR(1024) NOT NULL,
  mimetype VARCHAR(255) DEFAULT NULL,
  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pos_venda_field_options (
  id INT AUTO_INCREMENT PRIMARY KEY,
  field_name VARCHAR(255) NOT NULL,
  option_value VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS pos_venda_stages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  name VARCHAR(255) NOT NULL,
  position INT DEFAULT 0,
  is_initial TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projeto_checklist_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  projeto_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  completed TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  level INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS whatsapp_click_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  event VARCHAR(255) DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
